apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: roboshop
  labels: # these are deployment labels
    app: mongodb
    tier: db
    project: roboshop
    env: dev
spec:
  replicas: 1
  selector: # these labels should match with pod labels
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
      env: dev
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
        env: dev
    spec:
      containers:
      - name: mongodb
        image: pesiinfosys/mongodb:v1.0.0

